### ISSUE TITLE
ModuleNotFoundError: No module named 'pyparrot.Model'

### ISSUE THREAD

**Issue by KokeC137** [amymcgovern/pyparrot#213]
Hi,
First of all, thank you so much for sharing your work, it is being really usefull. I have an issue running demoBebopVision.py. I have a bebop2, but its not an issue of the drone so it does not matter i think,. when running demoBebopVision.py from cmd of windows, i have next issue:

Traceback (most recent call last):
  File "demoBebopVision.py", line 8, in <module>
    from pyparrot.Model import Model
ModuleNotFoundError: No module named 'pyparrot.Model'

Cannot guess what is happening, cause the others demo do work correctly. I have tried to fix the path to the folder pyparrot, but its still not working, and it is the only module is giving problems. Can u imagine what could be happening?

Thanks a lot!

**Comment by KokeC137** [comment]
When i say its not a drone issue, is because im not even conecting the Bebop, it gives the problem just running the script

**Comment by KokeC137** [comment]
> Hi,
> First of all, thank you so much for sharing your work, it is being really usefull. I have an issue running demoBebopVision.py. I have a bebop2, but its not an issue of the drone so it does not matter i think,. when running demoBebopVision.py from cmd of windows, i have next issue:
> 
> Traceback (most recent call last):
> File "demoBebopVision.py", line 8, in
> from pyparrot.Model import Model
> ModuleNotFoundError: No module named 'pyparrot.Model'
> 
> Cannot guess what is happening, cause the others demo do work correctly. I have tried to fix the path to the folder pyparrot, but its still not working, and it is the only module is giving problems. Can u imagine what could be happening?
> 
> Thanks a lot!

Ok i have already solved it. the problem was that the folder "C:\Users\jorge\anaconda3\Lib\site-packages\pyparrot" was not saved the module Model.py, so it was not found. i just copied there the file and it runs correctly ;D
