### ISSUE TITLE
bluepy.btle.BTLEException: Failed to execute mgmt cmd 'le on'

### ISSUE THREAD

**Issue by mulysatest** [amymcgovern/pyparrot#30]
First of all thank you for your super great effort and support on this project.

I managed to run the demo code successfully, however once I tried to run findMambo.py I got this error. Do you got any suggestion to solve it? I am using Linux tinkerboard 4.4.71+ on Asus Tinker Board.
```
~/pyparrot$ python findMambo.py 
Traceback (most recent call last):
  File "findMambo.py", line 27, in <module>
    devices = scanner.scan(10.0)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 679, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 617, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 276, in _mgmtCmd
    "Failed to execute mgmt cmd '%s'" % (cmd))
bluepy.btle.BTLEException: Failed to execute mgmt cmd 'le on'
```

**Comment by mulysatest** [comment]
I managed to solve problem using this command

sudo setcap 'cap_net_raw,cap_net_admin+eip' PATH/TO/LIB/python3.5/site-packages/bluepy/bluepy-helper

in my case

sudo setcap 'cap_net_raw,cap_net_admin+eip'  /usr/local/lib/python3.5/dist-packages/bluepy/bluepy-helper
